services:
  - type: web
    name: mystocks-client
    env: static
    staticPublishPath: frontend/dist # or frontend/build depending on your setup
    buildCommand: npm run build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
